language:
- php
- node_js
php:
- 7.1
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/
after_success:
- vendor/bin/php-coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
env:
  global:
  - secure: I1ZkknE5zapXdMzrkJ4kOOXF8U3krvalBbfwTonAjn554BsO5UfhmskxfGof20G+v3zsc4QXpb3JJysWsuHklizi/TU2tGXC8+7sM5ezbJbUZyagZ4ptluwaNOKlQ3Jq2kNjK/UrQmIsde1TOU/l9K4vC/anqT0U0KvFJvY+hwOuSM3V90GetzeISPTFD3C3G58LsX7zdrz/e10Iw4PGX2YIBqKjHJwdy9T0zz0M3b4eg+ii8m3ROWVGkuniewsv9dBrTFs3AYHQwz3U1FTYaLpCxw5h38Gg93mcaeLEPpKCPzp+QewsmwwH+L3fDsIm8F6SYVMKN3h83BfWV8nzu+/lseRzcq8gRR9KD8ErspnjCsViIM4XQFB7X0V3B68NkvL+ejuGQHIaJqgRxuHYzx5CFF2qUj/hQDoYGOB0ByOcjIthP/alLdGy8bbh99nXP3gtmud6WkEGyebbkHFpsOG5yQWLILXIyr9r6W4w2Q+GRv1GmIw8v1FzyFziLgeFbHfJzn6V5yvkGU9yaKFexh2vBgdx+m3EXgRItLw3v481AtisyIONCB/pQPcTSl3Elc0n8hwSkhM3qbSPzc8ULXnHKXRghpOBAn4NeLUAAGDJ3M8H7jkU+9t86R6yk+HAnB0e8J7e6rpbqU19Vd0H7w9O7UKyPlbP8CbocU9o+Q0=
  - secure: ekaga+VK7ZctKO3WmsjCHsDM4+t4Yp2OkYozZzGdlSqXxlY+EBjuo8qr8c8ReB15e7NS1Lm1kkZhtoR2sDeytWXswoUk+3TFd8xaKqg/qBox1rJ73CuXpUi+pKBpo17H++48Qe37YczLOFe7VHJpROH6ufPFm2C5sZFbaYcO7fZFIdYMJyvPg8h8HaPsWBSMuFWe84FHVM9zrIkp4AGPTfZ8GaK1EhmnVUAOjOHYLRqwKukp/2Pmm73HiZXBfCbsFggm/jwIX7HAsiGsPb0cB2JucOy9qa7Cg+lVLKTaDjrDvqTC422Fh2TRI460t9GiPUSPjNu0lbqHW6ctvfvxkaEBjKg1NYSdSU7n54THKLFGONiEbwQR4ZBGN73znjBvxd6zW17W6aQR7tjpk2iGz/QT4/lCRADwKT2ERI5VF04pLk3ZhrYOm8pz4impvXSN/5kGF3yLHRmG7df/ZI9/Nw3H1D00wAkoiuQ2yB01ySB/0FgswXZmv1ckcWOYTF0/B+M8GCFX6CUkC//WddeeK2dC8OxYxkUfrtUASckXedLEboeN/K3Kc+07OL96dvG1oxSzWH2CqGPubV4WSuvpLJ1IKG30z9B0bFcpjglu84DYHcKYQdYLUJNLYvwEqLY1mHSzxUtZz21YpVXOftkTbCVMJZMrFH9Y1TEqAiDisOs=
  - secure: 4JdD2Lhm8iYPGnc8xLGLDtRP2pGImn+s3Xw/LfmRJ1566rfkflfHejTFoD5aAyZjNBwFOWdH1YCU2LGB/b99njNi0WfTtSoUnXDmmlPCV9oi+7O1s6S06LDyPMugKVB2A5KAlHFx9ctzmHBzDy7ojYZSdWXBVEVuwDVrsQX1bQ1CJcguXonz9KMWST5WcYsbDm7k6nwdGSrSClvMrRbvy+u8V5Fo4/axZKQeu/N6dasf9G//2giVEno1BzImL7Kr9hLNhlKX/KOi4apn06gE0kxQKngbmFQHPFCXkDkVT4JROSFyC9TJLzde+aP311mxxhBcpyLIWvXIxnAiKWbpjpibRAbGpLBdE4VG9Irw21ctRjBLcT/SH+PZH0LqLTeNl/kTZFB/qBS/yUO0lUPFk4BiB8We0OcMIy0ymsYpFN3Stc6Zl+RdR9Nb5NNBn/4uKa3P8yWhoUhsDSOQ1RFaPxPNEqhvD6PuWDk29twzVSXBzQXJdkidUGbMdFflDBuY7yVI3Ira237CChFG9L4XqGquZBwqjI76sHOLXBCOxEnZKSWf0859O9EUHnRZk4zvK7Lv67eJ3UTGPWu8ZvAfWBS3Aj3boOgR1nFqtsJtmAjOsK7iffJoAMn65OfCpAY28Xu9ZmstS/iPF1B4bdNoytSusqiuIvPWVpBWny2hom4=
