language:
- php
- node_js
php:
- 7.1
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer update
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
env:
  global:
  - secure: ia1Qe17GZXyWOUemr4OkPZvuOEVNDRUlJ4VOM80c0DveNgTwZ4gvv7NaahksHeHSSxYrDCrJUEdZIk+9WW+wl6I8whN018uK6+/PUpZyv5e3ZDRb4rabkG9olZiEHQfjuOOYFjLMUfkJRjOESQNlZg8ngLMz6W4UFnvDbHKK6usuoNntAkaAXtwhuJPsQFt3Fff9MtjtcqL3KM5vtoV4AktHZPJZ1KEbhBE+UwXtWPSmsVgf5qVnnfsMEGqnSPzXP4TsDr77sSTYQ7dbL/C8VsqKI6wmrwJ9vsJ5ev9yqeKtu/L1pBgmGRGj22HNwINXj8WG3ri937A0VDAit6qNjO5RaAIhPvlxOmFWTMi/+fSxhqTLaELjJl0qfR0RJN+cgpH5jP9/yWf6jEPipWMxkGeexomANtTBP7wGgbuPo7xICG45nJQ8DTatV3me+PA93PWYjSwLw57SsqggLbTFOPnZ1kLNLQZwWNubcxEvBml8HbfABYhuf84gBr/6xdwBXg1lrQl0WAAiNzDKhTf6G7HaVADEFUvke82CPq8R0SK8EII3K/zmV1NaQpLVYKnYBlreLinKZKaNw8iJdkCEWVDTS3cY36UM2pg2c813VUWiRsgAoveQmCwTPTfALekNQ20NEiZcO8pbTdFQHaofTIjNeWVZ1JvWQGiNMqYa4oQ=
  - secure: mnpIX14H++D63mZCX9EOSntuMtoDNhRa6oeRL8sPDV4iijzz/386OklV4trp9f4MGsObxJdkZniQkDOCYKM6W3dPLsGceEKugV8jZu294eGXuZ5QVD+9qgxE3l9utDVyF4e0gxyxJcSz2ZVX9o4D9pHy86BJDqkefVyvcTdGxEECgsPqfoILWvEDAY5+b3yORTZyqnJshNlaqjr2wKB6NOtFg/aX33afRqFex6WVBvdl7e2B1h1pInwlbLfp3LGEzQ9w3Z+kmhoX7HXuPKIBNYJ72GSjylEcK+HVu21ncC5pvCIDOMOYZSyBMH7sKL9tgRGj8oV+k54T1/buhylQ+R3eJJgR5kgJZ0yqPrBQ4EhDsT6E5fC3M3CA66cq3vnnKOeXlPLwSPgzj9fzXqw55DoeVwzea1kfX5A+KTJyVAhGBm9rlePhrLT6B/hKR4f3K8ouwp6xwDryz45CRE/dKx44JCDMA0Pyg+axg5AuxNJEfUTUVt9mkfJybiWiK09omTd82D3pTVrXAwSG/BjYsZZpgmZgmewqYlGrUtBg1DswuCsdxyptUqlSI3/SQbEXw6byUKpUmHJwbSVJKf1baVSiPr4B6vbZbAkkVebEc5/KzsqFmXIWj5pgEuNATt9heW/jl0X8I5pIIOFBWFzqTbpBfmQl4nMkA4gq8aH7bZA=
  - secure: Y4YI2oIfpKuGmOPNhICSN9Z8+v4VPj2AzSfCeo6dKA4sdkoZ/J37vR1JOWBYO311jO7WKn0wnuSLrPsuh4hCnhPsqs1grfkqKlEEHl1f3oreopqfl0u0LTmjNo7nH5IgvblLIiHVj45ALG2FzDEKbOPZVt3ikiRPq8COAe+eyK2h2krFq2b8cHb6jEdOOaak6iSbff9rV/jdMkCcyzIcCidDXSj8O82sc4Bkvsfah4OswgQuSIbCg//lUlS8p46VYZVtgJDKNUyyH7vuG2Bz+MTs0RAlvk8O8ZEKTXhiB37LLlQcaMGZiSwrcEF0KcIDcVflNYlCO5pg1oZYbZeKUmeFF9JFS/STQqfO7rsPMj4KVxowdvmdMF+NXTuFMNYY0avanGxRnbdX18W+BUBY1wYeYh74554MQx69HeqwyYQIaCoCu06PEqRDzZuZRRpLEtlqLYE4Ij8Mgfe+kfEfAx0BIs+3/O++C5jh5kC6XolfimtL1rEvc3CVoNAfLNMQQSdN7ieQ2ocaHizd1Rtw16tr3SAC1VYFtp7UlES5crNFyKXDfxmh3tpvXkXjeigYMIDi4P0JRVqZjshob2f6Sv4lkOzoxAkaoyQyZ3yGVl2DZKTXbi6Ha32cY0n47g1I/f8H9SpF6MW1iufgpk/McA4t2TBHM1o/3YlXFg5k99I=
  - secure: DGQMzAWfeWlUCmkSVPsyVaWopdclBiMgvI93sOFAnQw8EjdH2hsW+XD1T2msw452Bvn/3j8BjWJlbWzKuf1YZVm10Layo7RqrMFGGMbMbQNqDT9g/XlcShlsjBdSh5pLSqQMrlHHujCXAy+IvwEEvb+ao/5t3gasI0rTn9rIwXp3Gj4BcIOaZ8lRmO3C2Eh1s9/jpEO2Y+GjM5WXlPZqV2Okx8+tYj7RJXu6giJR/kNb4y6YrrqKobKIvQVnV5RXJTNDHKmw0CqjMAr96kqOH5YGs1VpsiXT8ERgaHW0iyeOq8YxbhOorWb/Hdjl6XIolbw+Gr951WQ4gy1GJ7yiAT+DLemZjFQUmWU8MG5SS2nSRRRpvfvHi+zgGiagPCsqYs5VOa5mVP/SenjJ9rU8Q/81U5W5VoNa5MVad2OcWyy1K/yuxp1CUYAiW+/17x6D+zfmstH1HoCGfmdLHbqcrAvmkgvjDDQMa9Uj55Y77T2AeL/iuF0HGKL+EWuOZYAeCvmYFBw+TguewrrFmDAwSnkTaYa0u/9reojT/3nFg1ZKBZ9JmwUWDmc5/KrTcCpUxl5605KgkGsGCdmfGt8T52YLBkfuQOMP0innc4W0gdfA6PTwQmMef3fjut3CTXJqhA604TeHTeAemAwXdXu5LJaVzWIcO7S6UdYUVXWAsDs=
  - secure: yqEKrWqDgWhT09MwzHAQZFQzLcjiwJmdTlcoZjEmNTOT6UVFY4WegBHBOjonY9a9ZhAqgn3wfzpDkpDdQHe+uwkFA6GOT5Jr6EaMBAwkWNWgLo3ItcwGHI0dEOmXrfTn8qVoA8AQ6nZPVmCrkKFus3pmotSoREycCBdDggVH0zyczK2bVIyKQEZas7VvoLSNjpG4SYWoHI60ksEFZygLrb4UZTqNARaywtqBferB6fS+FshA49ubKICOvWRN3Se3bsh/v2O6C3AP/4nwi8xoV81BbgGJMlrd1CbeXD6V23FYOjkEjeRhegMCslP9lYkx/6WQ/h8zh0vbWYKrleOKhHtlQfQI7QaZsyE/UEQgNaKdUaaV3JoPKqCJKPp5IJljXIvaGile/FQ46FhQbwCkplf3rWfVk3MqdZ+t5C5YBLWVZPNiogwSQtAYSfqYY8i8NwzhUXdbnVRF5Daqu4ax0Ad3G9CUaHnotSs1ZZbHfNvdTCjeReOnkyOyo5JjLPCnRz5xSHVQaEr6Svmahced+vNP/v+MGA662spKmyEfOnuLvHagtXPfhR6Lv/ia+LPbyCia0u40OdXBVFbpuAh6XQYYJcjmYZ9QGLHsVJpHj3IOHX0UXS1K8AOYt+Yvm3MrqDa3grzSUBFqlVsQavjDcLMr3oJ+C939g7t1PeWraKk=
  - secure: a13SPEU2Wsb0cWcb3upz5HGw0UDZiMD5rhIuO/WgKbiEYJ4/Zg/zEk29l71KgAP9o8MGMmb3Wg8exnJxV9PINeg1OQcT+yi7tP1IG7ycRkwVuGRwisJhQ5ffwBOmzJs+AAW4tchGHgWOHOB7ltiuhpVotKa+H7CGz7qr6oyuhs5xAP4XF0IiiNMDthta4bg5aECXzjOsKhVWn0p80uY25+EpDkjqC+ksYs6sTfVeM1Jku8S569P5h/dY7+hC6gwOuTPIQv4eOcdrGTl/Yj7dwjzRSoGux/DRCEnx/QGhuDOAt9Zp60BawCElaZ1rTqolvhiImf5MpPa3cb17QxOeep+u/aLtChir/uLHzRwXanq7iaSQ4+jWBa/DICc54e9Y+/TbYSv6AzDuxsk2u1+ErswTl5ih55R1nERrG6YcVyQo6M05OuZEo4kXezt8YelOjzzqheaEWPa26HPATzmZfaje69J7tkvfDaphier4JZWPhkUcv98ByrcEULAidYxgEuSXdlSZTwL+lpyHWFnPheqyEcbS2TBFoG+pEeeSic+xhTsN8tqRDjeXZFUKl8LMQJ3e2HNwvpUOjryuGSUXyLhGhBOov1MmZySYlWFmnfwtoVW77d5Q/V43QglXhdXYlJbunUp15G+ecfp8/OlZy7ljd74/Kj7TcIgIWCXQUtM=
