dist: xenial
language: ruby
php:
- 7.1
node_js: '20.x'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/php-coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
env:
  global:
  - secure: zd0737eardMUap5e1p9psUeWBj07fpOwsOvT7bZs9C7OEw59hKI6UPfSk9/qxeNiJx3Ojya8kOodCWeGWAZMaZZiKMiRGtDVgb62jAQ4m2MZaYAYV+xDL/gsjSQkRWc7al5iwztqNcf2/oVcWuNxKuC1s+kdsaxBGTajAwtrr3YLjxWmaO6EPLRhQAvGK4JrmmEtaBQtK/F5d3kqqh4aa6Klu5vG01M9J81w6B/HqAFZJtANhH4C2uMAuPO6RNZECPvqpCTIQHw41s89mSYnlG3TvIhka4vF0HVJzCy8k738Ylr2LuTUW/RK1hmxzfAAMVg2mKj2vGc1qk6R5F9Pazxec8WGdJyHLWqq9dfTnIRyNPQZ0W9hISw/vmzFQyNEaBc4TzvU8105W8vvU+dGugaUSXnuZPIKIQC3NIBrpJIzwIG+2iw1OyYX7EVfRkicrsZfQsL8Sc7OSaCU8gUAeH8dd2gj0qVSwtX9+/ggn8M2RlQfTpwUdHwC1AZkknyGJFEUNv/NPE3aUm6/eCoLRfkWNg4DjzsE9HfLl/sfr+DyP5cuyLA9TST5GOf0GlohOfklbrYPSpfUDJjg/vOGFAjmNePLglNJdyHzbiRXQkprvtovBnAyH5MoPul3NacsHLPjeYJZ4VyoRCvw1iYJFlXjyLriU7hwaCxC4Cqidwo=
  - secure: sINu2XaCLGFCOgmxyjbsb1eF+GovWeRaOVJkR98NK8fzsuHApcYt5t3AcH5XcIflgQoj9HqjLmxR3Q+H/ETDV94JQ0ZbQowozmknAQ5g6Vq/vhvLaDuhWn3jP1UezS3rqebo23fwp8/dAxMqvPRmJgjFw2tuStaoD58EJZz70nVeF/IwaqTkC/+rqUjwo1Qd+mHCFP0aOPLRQokJyddiNP0206pS7FPnokL9nYxqC8/tFUEit6o2zEutOB7v5ky9OXbuVvCUdOe3ybFmSVtEdmokkuXl/jfwp1YPcXiYP3ibIx2D9T7H32oaIkv8NYNuWYMmhEywVGxrnHlJBDPGlfPuUHLFNRwb/0IbngZ8nvAVLQrRyeOcWM1RZNitvuEVLk4NhKXi6tXbhHLW6xIHvvp9wErv4Z3tSH0tSAxmzNz5HO8cOVf3biHcbOMcAHXx8bM+/68P8wE8PZF+MYkKtEVCHzlvsboo4gkS7Z1cCP+K1sZRo4kLNZJ98MgpoOUqZHV9LbF4R31PuwlZ7+ALb3zJcHeKiA9/jOQevYBurxjtm4Da7nux6v9DbYt0TPfHvKCqfnVb9IH3T3cB8DAk0E/toh9n+8guKwka2HgEPTWnWwEN1oyjac1iFuDKpWjMHZXQ9jHigUf4nQeY+TOs1jY8BOLc95xlrDFGqsAZuHg=
